<a href="https://colab.research.google.com/github/dimsvxyz/EDA---Exploratory-Data-Analysis/blob/main/Filter%20data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

file_path = "Data Mental Health.xlsx"
df = pd.read_excel(file_path)

print("Kolom tersedia:", df.columns.tolist())
print("Nilai unik Gender:", df['Gender'].unique())

df_female = df[df['Gender'].str.lower() == 'female']
print(f"Jumlah total data: {len(df)}")
print(f"Jumlah data Female: {len(df_female)}")
print(f"Persentase Female: {len(df_female)/len(df)*100:.2f}%")

df_female.head(10)

Kolom tersedia: ['id', 'Name', 'Gender', 'Age', 'City', 'Working Professional or Student', 'Profession', 'Academic Pressure', 'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction', 'Sleep Duration', 'Dietary Habits', 'Degree', 'Have you ever had suicidal thoughts ?', 'Work/Study Hours', 'Financial Stress', 'Family History of Mental Illness']
Nilai unik Gender: ['Male' 'Female']
Jumlah total data: 93800
Jumlah data Female: 42538
Persentase Female: 45.35%

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
1,140701,Sanya,Female,580,Kolkata,Working Professional,Educational Consultant,NaN,20.0,NaN,NaN,40.0,Less than 5 hours,Moderate,B.Ed,No,60,40,No
3,140703,Nalini,Female,230,Rajkot,Student,NaN,50.0,NaN,684.0,10.0,NaN,More than 8 hours,Moderate,BSc,Yes,100,40,No
7,140707,Ritika,Female,280,Mumbai,Working Professional,Customer Support,NaN,50.0,NaN,NaN,30.0,7-8 hours,Healthy,BA,Yes,0,20,No
8,140708,Navya,Female,210,Surat,Student,NaN,10.0,NaN,739.0,30.0,NaN,Less than 5 hours,Healthy,BBA,No,80,10,Yes
14,140714,Garima,Female,450,Mumbai,Working Professional,HR Manager,NaN,50.0,NaN,NaN,40.0,5-6 hours,Healthy,MA,Yes,60,10,Yes
15,140715,Anvi,Female,290,Thane,Working Professional,Research Analyst,NaN,20.0,NaN,NaN,50.0,7-8 hours,Healthy,MBA,No,100,10,No
18,140718,Riya,Female,490,Nagpur,Working Professional,Chemist,NaN,40.0,NaN,NaN,20.0,7-8 hours,Moderate,M.Pharm,No,90,30,No
20,140720,Rashi,Female,260,Ghaziabad,Student,NaN,30.0,NaN,863.0,50.0,NaN,More than 8 hours,Moderate,BBA,Yes,100,40,Yes
22,140722,Anjali,Female,410,Chennai,Working Professional,HR Manager,NaN,10.0,NaN,NaN,10.0,5-6 hours,Moderate,BA,No,70,30,Yes
24,140724,Suhani,Female,250,Jaipur,Student,NaN,50.0,NaN,673.0,20.0,NaN,7-8 hours,Moderate,BHM,Yes,20,30,No

In [2]:
df_age = df[df['Age'] < 300]

print("Jumlah Total Data:", len(df))
print("Jumlah Data dengan Usia < 300:", len(df_age))
print("Persentase (%):", round(len(df_age)/len(df)*100, 2))

df_age.head(10)

Jumlah Total Data: 93800
Jumlah Data dengan Usia < 300: 23671
Persentase (%): 25.24

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
3,140703,Nalini,Female,230,Rajkot,Student,NaN,50.0,NaN,684.0,10.0,NaN,More than 8 hours,Moderate,BSc,Yes,100,40,No
5,140705,Kartik,Male,290,Mumbai,Working Professional,Customer Support,NaN,20.0,NaN,NaN,30.0,More than 8 hours,Moderate,B.Com,No,30,20,Yes
7,140707,Ritika,Female,280,Mumbai,Working Professional,Customer Support,NaN,50.0,NaN,NaN,30.0,7-8 hours,Healthy,BA,Yes,0,20,No
8,140708,Navya,Female,210,Surat,Student,NaN,10.0,NaN,739.0,30.0,NaN,Less than 5 hours,Healthy,BBA,No,80,10,Yes
9,140709,Harsha,Male,210,Jaipur,Working Professional,NaN,NaN,50.0,NaN,NaN,10.0,Less than 5 hours,Healthy,Class 12,Yes,100,40,No
13,140713,Reyansh,Male,180,Visakhapatnam,Working Professional,NaN,NaN,50.0,NaN,NaN,20.0,5-6 hours,Moderate,Class 12,Yes,0,20,No
15,140715,Anvi,Female,290,Thane,Working Professional,Research Analyst,NaN,20.0,NaN,NaN,50.0,7-8 hours,Healthy,MBA,No,100,10,No
19,140719,Kiran,Male,280,Lucknow,Student,NaN,50.0,NaN,603.0,30.0,NaN,7-8 hours,Moderate,MA,No,110,30,Yes
20,140720,Rashi,Female,260,Ghaziabad,Student,NaN,30.0,NaN,863.0,50.0,NaN,More than 8 hours,Moderate,BBA,Yes,100,40,Yes
24,140724,Suhani,Female,250,Jaipur,Student,NaN,50.0,NaN,673.0,20.0,NaN,7-8 hours,Moderate,BHM,Yes,20,30,No